// 365 Daily Messages (Warm, respectful, non-romantic, inspiring)
export const DAILY_MESSAGES = [
  "May today bring peace to your heart.",
  "I hope today gives you one unforgettable smile.",
  "Take care of yourself today.",
  "The world became brighter because you exist.",
  "Don't forget to smile today.",
  "Someone wished good things for you today.",
  "Keep believing in yourself.",
  "May happiness quietly find you.",
  "Your kindness is a light in this world.",
  "May your path today be smooth and gentle.",
  "Take a deep breath; you are doing wonderfully.",
  "May your day be filled with quiet moments of joy.",
  "You bring a unique warmth to the lives of many.",
  "I hope you find beauty in the simplest things today.",
  "May your mind be calm and your heart be light.",
  "Your presence is a gift to those around you.",
  "May today bring you gentle reminders of your worth.",
  "Be gentle with yourself today.",
  "May the stars always guide you safely.",
  "Wishing you a day as radiant as your spirit.",
  "May you feel supported and appreciated today.",
  "You deserve all the goodness today has to offer.",
  "May a quiet peace accompany you through the hours.",
  "Your strength is quiet but deeply inspiring.",
  "May today offer you a sweet moment of rest.",
  "I hope today brings a lovely surprise your way.",
  "Your sincerity makes the world a better place.",
  "May you feel completely at ease today.",
  "Your path is unique, and you are walking it beautifully.",
  "May you be surrounded by kindness and genuine respect.",
  "Wishing you a calm mind and a joyful heart.",
  "Your effort and care never go unnoticed.",
  "May today bring a refreshing breeze into your life.",
  "I hope today brings you closer to your quiet dreams.",
  "May your interactions today be warm and sincere.",
  "You are an anchor of grace in a fast-moving world.",
  "May you find a reason to smile in every hour today.",
  "Your heart is beautiful; never let the world change that.",
  "May a gentle light guide your thoughts today.",
  "Wishing you quiet confidence in everything you do.",
  "May you feel valued for exactly who you are.",
  "I hope today offers you a chance to breathe deeply.",
  "Your authenticity is your greatest strength.",
  "May today bring you a sense of accomplishment.",
  "Wishing you gentle moments that make you feel alive.",
  "May you walk with grace and confidence today.",
  "Your voice is a comfort to those who hear it.",
  "May today bring you a cozy sense of comfort.",
  "I hope today whispers encouragement to your soul.",
  "May your day be filled with warm connections.",
  "You are a rare and precious person to me.",
  "May today bring you peace, clarity, and soft focus.",
  "Wishing you a day of effortless flow and ease.",
  "May you look back on today with a gentle smile.",
  "Your courage is beautiful and quiet.",
  "May today be a gentle chapter in your journey.",
  "I hope today brings you a sense of deep belonging.",
  "May your heart feel light and untroubled.",
  "Your capacity for kindness is limitless.",
  "May today treat you with the utmost tenderness.",
  "Wishing you a day filled with quiet grace.",
  "May you find inspiration in unexpected places today.",
  "Your focus and dedication are truly admirable.",
  "May today bring you a step closer to inner stillness.",
  "I hope today offers you beautiful spaces of reflection.",
  "Your thoughtfulness makes people feel truly seen.",
  "May your day be painted with soft, pleasant colors.",
  "Wishing you safety, warmth, and complete tranquility.",
  "May you find joy in the work of your hands today.",
  "Your presence brings a soothing calm.",
  "May today be generous with its quiet blessings.",
  "I hope you meet people who appreciate your warmth today.",
  "Your patience is a remarkable strength.",
  "May your day be as steady and comforting as an anchor.",
  "Wishing you gentle laughter and lighthearted hours.",
  "May you feel completely content with where you are.",
  "Your gentle nature is a wonderful gift.",
  "May today bring a lovely clarity to your dreams.",
  "I hope you feel the warmth of distant good wishes today.",
  "May your day be free of worry and full of light.",
  "You are capable of beautiful things.",
  "May today invite you to slow down and appreciate the now.",
  "Wishing you a day of soft light and warm tea.",
  "May your thoughts be gentle companions today.",
  "Your wisdom is a quiet, reassuring guide.",
  "May today unlock a new sense of quiet wonder for you.",
  "I hope you find peace in your own silence today.",
  "Your enthusiasm brings beautiful energy.",
  "May your day be balanced, calm, and productive.",
  "Wishing you comfortable silences and meaningful words.",
  "May you be shielded from any harshness today.",
  "Your resilience is a silent, beautiful melody.",
  "May today bring you closer to what truly matters.",
  "I hope you feel the comfort of being respected today.",
  "Your creative spirit is a joy to observe.",
  "May your day be filled with gentle transitions.",
  "Wishing you a heart that is light and free of burdens.",
  "May today reward your efforts in unexpected ways.",
  "Your kindness leaves a beautiful, lasting trail.",
  "May today bring you absolute clarity and focus.",
  "I hope you find comfort in your favorite things today.",
  "Your dedication to goodness is inspiring.",
  "May your day be as refreshing as morning dew.",
  "Wishing you steady progress and deep peace.",
  "May you feel completely supported by the universe today.",
  "Your humility and grace are deeply moving.",
  "May today bring you a soft sense of contentment.",
  "I hope today brings you a quiet, happy memory.",
  "Your spirit is steady, reliable, and bright.",
  "May your day be filled with gentle understandings.",
  "Wishing you moments of absolute stillness today.",
  "May you feel the warmth of my genuine care today.",
  "Your perspective is a valuable and beautiful gift.",
  "May today flow with effortless grace.",
  "I hope you feel proud of the person you are.",
  "Your quiet confidence is incredibly magnetic.",
  "May your day be free of clutter and full of peace.",
  "Wishing you gentle guidance in every decision today.",
  "May you find a quiet harbor in any storm today.",
  "Your capacity to care is a beautiful strength.",
  "May today bring you simple, uncomplicated joy.",
  "I hope today treats your thoughts with kindness.",
  "Your warm heart is a shelter for others.",
  "May your day be as beautiful as a quiet forest.",
  "Wishing you safety, peace, and quiet reassurance.",
  "May you feel the joy of being fully understood today.",
  "Your journey is unfolding exactly as it should.",
  "May today bring you a pleasant surprise of light.",
  "I hope today reminds you of your inner strength.",
  "Your gentle words are more powerful than you know.",
  "May your day be structured with peace and productivity.",
  "Wishing you a quiet, cozy evening after a good day.",
  "May you be blessed with people who truly listen to you.",
  "Your elegance is natural and timeless.",
  "May today be a canvas of gentle and warm moments.",
  "I hope today gives you a reason to pause and smile.",
  "Your genuine nature is a rare treasure.",
  "May your day be filled with gentle, constructive energy.",
  "Wishing you deep focus and serene thoughts today.",
  "May you feel a beautiful connection to the stars tonight.",
  "Your quiet endurance is incredibly powerful.",
  "May today bring a refreshing pause to your busy life.",
  "I hope you find comfort in your own breathing today.",
  "Your presence is a reminder of gentleness.",
  "May your day be filled with soft and pleasant discoveries.",
  "Wishing you a day of steady steps and calm breathing.",
  "May you feel completely safe and valued today.",
  "Your heart deserves all the peace it gives to others.",
  "May today bring a beautiful simplicity to your mind.",
  "I hope today rewards your kindness tenfold.",
  "Your focus on what is good is a blessing.",
  "May your day be guarded by quiet, positive energies.",
  "Wishing you a day of beautiful, unspoken connections.",
  "May you find ease in every single task today.",
  "Your life is a beautiful work of art.",
  "May today bring you a soft, comforting reassurance.",
  "I hope today makes you feel deeply appreciated.",
  "Your quiet determination is deeply moving.",
  "May your day be as bright as a field of sunflowers.",
  "Wishing you warm thoughts and complete peace of mind.",
  "May you be surrounded by people who respect your silence.",
  "Your authenticity is a beautiful compass.",
  "May today offer you a sweet and gentle space of rest.",
  "I hope today brings you closer to your personal peace.",
  "Your strength lies in your quiet kindness.",
  "May your day be filled with lighthearted laughter.",
  "Wishing you a steady heart and an open mind today.",
  "May you find absolute comfort in being yourself.",
  "Your warmth is like a soft campfire on a cool evening.",
  "May today bring a delightful spark to your imagination.",
  "I hope today reminds you how much you matter.",
  "Your focus and clarity are exceptionally beautiful.",
  "May your day be free of unnecessary noise.",
  "Wishing you a gentle and supportive environment today.",
  "May you feel a deep, quiet joy within your soul.",
  "Your sincerity is felt by everyone you meet.",
  "May today bring you a step closer to your goals.",
  "I hope you find peace in the sounds of nature today.",
  "Your patient heart is a beautiful thing.",
  "May your day be filled with gentle accomplishments.",
  "Wishing you a warm, relaxing, and peaceful day.",
  "May you feel the steady support of those who care.",
  "Your presence makes any room feel safer and warmer.",
  "May today bring you clear thoughts and soft feelings.",
  "I hope today gives you a moment of pure inspiration.",
  "Your resilience is a quiet, beautiful light.",
  "May your day be as smooth as a calm lake at dawn.",
  "Wishing you genuine warmth in all your interactions.",
  "May you feel completely content with your progress.",
  "Your gentle spirit is a wonderful anchor.",
  "May today bring a refreshing clarity to your mind.",
  "I hope you feel surrounded by distant, warm blessings.",
  "Your kindness is a powerful force for good.",
  "May your day be filled with gentle, helpful moments.",
  "Wishing you a day of peaceful focus and clear sight.",
  "May you find joy in the simple act of being today.",
  "Your life is a beautiful gift to this world.",
  "May today bring you a soft, radiant peace.",
  "I hope today gives you a reason to celebrate yourself.",
  "Your quiet confidence is deeply reassuring.",
  "May your day be guarded by gentle thoughts.",
  "Wishing you comfortable spaces and warm encounters.",
  "May you feel the quiet joy of being alive today.",
  "Your warmth is a steady light in a cold world.",
  "May today bring a beautiful harmony to your actions.",
  "I hope today makes you feel entirely at home.",
  "Your gentle nature is a masterclass in grace.",
  "May your day be as comforting as a warm blanket.",
  "Wishing you absolute peace in your quiet moments.",
  "May you feel a beautiful connection to your dreams today.",
  "Your sincerity is a breath of fresh air.",
  "May today bring you a gentle, reassuring hug from life.",
  "I hope you find joy in the quiet of the morning.",
  "Your patient spirit is highly inspiring.",
  "May your day be filled with pleasant, warm breezes.",
  "Wishing you a day of clear skies and steady paths.",
  "May you feel completely valued for your gentle soul.",
  "Your presence is a comfort that needs no words.",
  "May today bring a soft clarity to your journey.",
  "I hope today whispers beautiful truths to your heart.",
  "Your resilience is a quiet work of genius.",
  "May your day be filled with sweet and simple victories.",
  "Wishing you warm connections and genuine smiles.",
  "May you feel completely at peace with your decisions.",
  "Your gentle strength is a magnificent shield.",
  "May today bring a lovely flow to your thoughts.",
  "I hope today reminds you of your incredible worth.",
  "Your authentic heart is a beautiful sanctuary.",
  "May your day be as bright as a twinkling star.",
  "Wishing you safe spaces and gentle minds today.",
  "May you find a quiet joy in your everyday tasks.",
  "Your life is a beautiful light in the universe.",
  "May today bring you a soft, comforting breeze.",
  "I hope today makes you feel deeply valued and seen.",
  "Your quiet determination is an inspiration.",
  "May your day be filled with peaceful progress.",
  "Wishing you warm thoughts and complete serenity.",
  "May you be surrounded by deep, genuine respect today.",
  "Your sincere nature is a rare and beautiful gem.",
  "May today bring a pleasant pause to your thoughts.",
  "I hope you find comfort in your breathing patterns today.",
  "Your gentle energy is a soothing balm for others.",
  "May your day be as calm as a summer night.",
  "Wishing you steady progress and absolute clarity.",
  "May you feel a warm connection to your purpose today.",
  "Your patience is a beautiful, silent melody.",
  "May today bring a refreshing perspective to your life.",
  "I hope today offers you a chance to rest deeply.",
  "Your thoughtfulness makes a real difference in the world.",
  "May your day be filled with warm, quiet moments.",
  "Wishing you gentle guidance and complete safety.",
  "May you find comfort in your own company today.",
  "Your quiet confidence is a powerful anchor.",
  "May today bring simple, uncomplicated happiness.",
  "I hope today treats your efforts with kindness.",
  "Your warm heart is a true shelter.",
  "May your day be filled with gentle understandings.",
  "Wishing you soft light and cozy moments today.",
  "May you feel completely safe and deeply appreciated.",
  "Your gentle words are a comforting melody.",
  "May today bring a beautiful balance to your spirit.",
  "I hope today reminds you of your beautiful light.",
  "Your presence is a reminder of peace and grace.",
  "May your day be as steady and reliable as the earth.",
  "Wishing you a day of gentle steps and happy thoughts.",
  "May you find absolute peace in where you are.",
  "Your authenticity is a quiet, beautiful power.",
  "May today bring a pleasant clarity to your heart.",
  "I hope today gives you a reason to smile widely.",
  "Your presence in my life is a wonderful gift.",
  "May your day be filled with cozy, comfortable hours.",
  "Wishing you deep focus and lighthearted moments.",
  "May you feel completely connected to the quiet beauty around you.",
  "Your quiet endurance is incredibly inspiring.",
  "May today bring you a sweet and gentle reminder of peace.",
  "I hope you find joy in the simplest interactions today.",
  "Your patient heart is a true masterpiece.",
  "May your day be structured with light and grace.",
  "Wishing you warm encounters and gentle conversations.",
  "May you feel completely secure in your quiet strength.",
  "Your life is a beautiful, quiet melody of grace.",
  "May today bring a refreshing pause to your worries.",
  "I hope today makes you feel deeply content.",
  "Your sincere spirit is a steady compass.",
  "May today be a gentle step forward in your journey.",
  "I hope you find comfort in the beauty of the stars tonight."
];

// 365 Daily Wishes (Elegant, non-romantic, focusing on growth, peace, happiness)
export const DAILY_WISHES = [
  "May every sunrise bring hope.",
  "May your dreams slowly become reality.",
  "May kindness always surround you.",
  "May your heart stay peaceful.",
  "May your paths always lead to gentle light.",
  "May you find quiet strength in difficult moments.",
  "May you always walk with confidence and grace.",
  "May happiness quietly find you wherever you are.",
  "May your mind be a harbor of calm thoughts.",
  "May your sincere efforts bring beautiful rewards.",
  "May your spirit always remain light and free.",
  "May you be surrounded by people who appreciate your warmth.",
  "May your days be balanced with work and quiet rest.",
  "May you always remember your incredible worth.",
  "May you find comfort in your own breathing and silence.",
  "May the stars always guide your steps safely.",
  "May your life be painted with gentle and warm colors.",
  "May your heart stay open to the beauty of the universe.",
  "May a quiet confidence guide you through every choice.",
  "May you always have a reason to smile every single day.",
  "May your sincerity always be met with genuine respect.",
  "May you find absolute comfort in exactly who you are.",
  "May your memories always be warm and comforting.",
  "May the work of your hands bring quiet pride.",
  "May your thoughts always be gentle companions.",
  "May you be shielded from any harshness or doubt.",
  "May your quiet endurance lead to radiant success.",
  "May every conversation you have leave you feeling valued.",
  "May your dreams be deep, peaceful, and refreshing.",
  "May kindness always be your compass and guide.",
  "May you find joy in the simple, everyday moments.",
  "May your patience always reward you with peace.",
  "May your warm presence continue to comfort others.",
  "May the universe quietly whisper encouragement to you.",
  "May you feel supported by the thoughts of those who care.",
  "May your actions always align with your authentic heart.",
  "May you walk with quiet dignity in every path you choose.",
  "May today's efforts blossom into tomorrow's joy.",
  "May your mind stay clear and your focus stay steady.",
  "May you find quiet harbors in any of life's storms.",
  "May your capacity to care remain a beautiful strength.",
  "May you always find beauty in the quiet of the night.",
  "May a gentle peace accompany your every hour.",
  "May you feel completely content with your progress.",
  "May your gentle words always carry comforting power.",
  "May you look back on every chapter with quiet gratitude.",
  "May your unique path unfold beautifully and steadily.",
  "May you be blessed with meaningful, comfortable silences.",
  "May your spirit stay resilient and untroubled.",
  "May happiness find a permanent home in your heart.",
  "May your inner light continue to shine quietly and bright.",
  "May you always find comfort in your favorite spaces.",
  "May the universe grant you clarity and serene focus.",
  "May you always walk in fields of peace and respect.",
  "May your thoughtfulness always return to you in warmth.",
  "May you feel completely safe and deeply understood.",
  "May your journey be full of pleasant, gentle surprises.",
  "May your heart be a sanctuary of kindness.",
  "May your thoughts always dwell on things that lift you up.",
  "May you find effortless flow in everything you do.",
  "May you always feel proud of the person you are.",
  "May your quiet confidence lead you to beautiful places.",
  "May your day be filled with steady steps and calm breathing.",
  "May you be surrounded by the quiet grace of nature.",
  "May your life be a beautiful reflection of your values.",
  "May you find comfort in the slow, natural pace of things.",
  "May your sincere nature continue to inspire those around you.",
  "May your dreams slowly take root and blossom.",
  "May you feel the warmth of distant, heartfelt wishes.",
  "May you be blessed with absolute peace of mind.",
  "May your journey be steady, beautiful, and completely yours.",
  "May your mind be free of clutter and full of light.",
  "May you always find encouragement when you need it most.",
  "May your interactions always be sincere and warm.",
  "May your heart stay untroubled by the noise of the world.",
  "May you find joy in the quiet act of listening.",
  "May your quiet strength always protect your peace.",
  "May you feel completely aligned with your true purpose.",
  "May your days be generous with quiet, sweet blessings.",
  "May your life unfold as a masterpiece of gentleness.",
  "May you always find a reason to celebrate your existence.",
  "May your thoughts be as clear and steady as water.",
  "May you walk with ease, clarity, and soft confidence.",
  "May your patience lead you to perfect timing.",
  "May your spirit always find comfort in the beauty of art.",
  "May you be surrounded by steady and reliable people.",
  "May your warm heart never grow tired of being kind.",
  "May you find rest, rejuvenation, and deep focus.",
  "May the path ahead be wide, clear, and full of light.",
  "May your sincerity always be your greatest power.",
  "May you feel completely secure in your quiet grace.",
  "May your dreams guide you to incredible, serene heights.",
  "May your days be filled with comfortable, lighthearted hours.",
  "May you find a quiet joy in your everyday rituals.",
  "May your heart stay steady and your mind stay free.",
  "May you always feel appreciated for exactly who you are.",
  "May your actions bring gentle comfort to your soul.",
  "May you always be accompanied by positive and serene energy.",
  "May your journey be filled with beautiful, steady growth.",
  "May the stars always shine their quiet approval on you.",
  "May your thoughts be gentle companions through the dark.",
  "May you walk with absolute peace in your decisions.",
  "May your warm presence always be a source of calm.",
  "May you always find cozy spaces to rest and think.",
  "May your focus on goodness bring you deep happiness.",
  "May you look forward to every sunrise with calm hope.",
  "May your life be a beautiful, quiet song of grace.",
  "May you find inspiration in every single breath.",
  "May you be surrounded by people who respect your dreams.",
  "May your sincerity always shine through any cloud.",
  "May you feel completely content with where you are.",
  "May your thoughts be like stars—guiding and bright.",
  "May you always walk with a heart full of gratitude.",
  "May you find a quiet harbor of comfort in your mind.",
  "May your capacity for kindness never fail to warm you.",
  "May you be blessed with absolute clarity of vision.",
  "May your steps be steady, purposeful, and peaceful.",
  "May your life be free of hurry and full of meaning.",
  "May your sincere nature always bring you closer to truth.",
  "May you find joy in the simple sound of silence.",
  "May your heart stay resilient, steady, and bright.",
  "May the stars always mirror the courage in your soul.",
  "May your path be paved with kindness and gentle respect.",
  "May you always find comfort in the sound of distant rain.",
  "May your mind stay clear of any unnecessary worry.",
  "May you walk with a beautiful and gentle confidence.",
  "May your warm heart always stay safe and valued.",
  "May you find absolute clarity in your quietest moments.",
  "May your dreams always carry you to peaceful places.",
  "May you look forward to the future with peaceful eyes.",
  "May your sincere connections always grow stronger.",
  "May you always feel at home in your own mind.",
  "May your steps be guided by wisdom and soft light.",
  "May you be blessed with a steady and calming environment.",
  "May your patient heart always find its perfect reward.",
  "May your life be a sanctuary of calm and serene focus.",
  "May you find inspiration in the changing of seasons.",
  "May your quiet determination always lead to peace.",
  "May you feel the steady, reassuring warmth of connection.",
  "May your thoughts stay focused on what is genuine and true.",
  "May you walk with grace, integrity, and light steps.",
  "May your warm presence continue to heal and comfort.",
  "May you find comfort in reading, thinking, and being.",
  "May your spirit stay bright, curious, and gentle.",
  "May you always have a peaceful sanctuary to return to.",
  "May your capacity for patience bring you deep wisdom.",
  "May your life be filled with gentle, helpful transitions.",
  "May you always feel completely supported and cared for.",
  "May your mind stay steady in times of change.",
  "May you find joy in the simple beauty of a blooming flower.",
  "May your sincere efforts always lead you to fulfillment.",
  "May your heart remain a vessel of quiet, profound joy.",
  "May the stars always whisper peace to your sleeping mind.",
  "May you walk in the light of your own quiet truth.",
  "May your warm heart always stay untamed and free.",
  "May you find comfort in the steady rhythm of your breathing.",
  "May you look forward to every day with quiet confidence.",
  "May your journey be full of meaningful silences and soft laughter.",
  "May you be surrounded by people who truly listen to your soul.",
  "May your sincere path always lead you to high grounds.",
  "May you find absolute peace in the present moment.",
  "May your mind stay a sanctuary of serene, positive thoughts.",
  "May you walk with absolute dignity, grace, and light.",
  "May your warm nature always attract genuine goodness.",
  "May you find comfortable, cozy spaces wherever you go.",
  "May your life unfold as a beautiful tapestry of peace.",
  "May you always feel proud of the silent battles you win.",
  "May your quiet confidence unlock every door of opportunity.",
  "May your dreams be clear, comforting, and inspiring.",
  "May you look back with pride and look forward with hope.",
  "May your sincere efforts bring you deep and lasting peace.",
  "May your heart stay anchored in kindness and respect.",
  "May you always find a reason to smile under the stars.",
  "May your steps be steady, light, and full of grace.",
  "May your life be filled with beautiful, quiet accomplishments.",
  "May you find absolute comfort in your quietest spaces.",
  "May your patient spirit always find its perfect resting place.",
  "May you always feel the warmth of distant, loving thoughts.",
  "May your path stay smooth, clear, and brightly lit.",
  "May your mind be a harbor of beautiful and steady focus.",
  "May you walk with quiet elegance through every hour.",
  "May your warm presence continue to bring soft joy.",
  "May you find rest and clarity in your favorite rituals.",
  "May your spirit always remain untamed, bright, and free.",
  "May you always feel fully respected for who you are.",
  "May your thoughts be like gentle guides through the night.",
  "May your journey lead you to fields of complete contentment.",
  "May you be blessed with genuine, simple, and warm encounters.",
  "May your sincere heart always remain your greatest guide.",
  "May you find quiet joy in every task of your hands.",
  "May your life be a beautiful sanctuary of gentle growth.",
  "May you always find encouragement in the sky's silver stars.",
  "May your steps stay steady, light, and full of joy.",
  "May you always walk in the warmth of quiet, respectful love.",
  "May your mind stay a clear mirror of your genuine soul.",
  "May you find absolute peace in the slow flow of time.",
  "May your heart stay strong, steady, and full of kindness.",
  "May the stars always light your way with silver threads.",
  "May you walk with a peaceful mind and an open heart.",
  "May your warm nature always be met with matching warmth.",
  "May you find comfort and reassurance in every deep breath.",
  "May you look forward to the future with absolute calm.",
  "May your sincere bonds grow stronger and deeper with time.",
  "May you always feel at home in your beautiful thoughts.",
  "May your steps lead you to gentle harbors of comfort.",
  "May you be blessed with absolute focus and clarity.",
  "May your patient heart always find its perfect harmony.",
  "May your life unfold beautifully, at your own perfect pace.",
  "May you always find comfort in the beauty of simple things.",
  "May your quiet strength always protect your gentle heart.",
  "May you feel completely aligned with the stars tonight.",
  "May your thoughts be gentle companions as you rest.",
  "May your path be paved with soft stardust and quiet wishes.",
  "May your steps be light, steady, and completely untroubled.",
  "May you find absolute peace in the quiet of your sanctuary.",
  "May your life always remain a beautiful, quiet work of art.",
  "May you look back with gratitude and forward with serene hope.",
  "May your sincere nature continue to make the world a better place."
];

// 100 Welcome Back messages (Polite, comforting, deeply respectful)
export const WELCOME_BACK_MESSAGES = [
  "Welcome back Deepal ❤️ I'm happy to see you again.",
  "Today's surprise is waiting. Welcome back, Deepal.",
  "This little universe missed you, Deepal.",
  "Welcome back. I hope you've had a gentle day.",
  "I'm glad your path led you back here today.",
  "Step inside and breathe. Welcome back, Deepal.",
  "A quiet moment of peace is waiting for you. Welcome back.",
  "The stars are glowing brighter now that you're back.",
  "Welcome back to your digital sanctuary, Deepal.",
  "I hope today treated you with kindness. Welcome back.",
  "Your quiet space has been waiting for you.",
  "Welcome back. Take a moment to slow down and rest.",
  "Always a joy to see you. Welcome back, Deepal.",
  "The constellations are aligned for your return.",
  "Welcome back. May this space bring peace to your mind.",
  "I'm glad you're here. Let's find some quiet joy today.",
  "Welcome back. Today's unique chapter is ready.",
  "A gentle reminder of goodness is waiting. Welcome back.",
  "Your presence always adds a beautiful warmth to this sphere.",
  "Welcome back, Deepal. I hope you find comfort here.",
  "I've kept the stars lit for your return.",
  "Welcome back. Breathe in, let go, and rest.",
  "The stardust harp is waiting. Welcome back, Deepal.",
  "I'm happy to welcome you back to your peaceful harbor.",
  "Welcome back. I hope today brought you reasons to smile.",
  "A special stardust wish is waiting inside the jar.",
  "Welcome back. May the quiet here settle your mind.",
  "It is always a privilege to welcome you back, Deepal.",
  "Welcome back. Your gentle spirit is always felt here.",
  "Today's light is prepared especially for your return.",
  "Welcome back, Deepal. May you feel safe and appreciated here.",
  "I hope you've walked with grace today. Welcome back.",
  "Your digital sanctuary missed your quiet warmth.",
  "Welcome back. The wishing locket is ready for your thoughts.",
  "Glad to see you again. Let the stars soothe your mind.",
  "Welcome back, Deepal. Take all the time you need here.",
  "Today's custom surprise is unlocked and ready.",
  "Welcome back. I hope you find a cozy spot to rest your eyes.",
  "The celestial spheres are glad you've returned.",
  "Welcome back. A quiet, warm message is waiting for you.",
  "Your sanctuary is always open, and always glad to see you.",
  "Welcome back, Deepal. May your thoughts stay peaceful today.",
  "Step into the stillness. Welcome back.",
  "I hope you had a light and steady day. Welcome back.",
  "Welcome back. Let's release any worries to the stars.",
  "The glowing locket of July MMXXVI welcomes you back.",
  "Welcome back, Deepal. You deserve this quiet moment.",
  "Always a comforting sight to see you. Welcome back.",
  "The stardust elements are dancing in celebration of your return.",
  "Welcome back. Let the quiet hum bring calm to your heart.",
  "Welcome back, Deepal. The jar of wishes is filled for you.",
  "Your peaceful escape is ready. Welcome back.",
  "Welcome back. I hope you find the comfort you deserve today.",
  "I'm glad you took a moment to return here.",
  "Welcome back, Deepal. May your breathing be deep and steady.",
  "The golden fireflies have gathered to welcome you back.",
  "Welcome back. Your chapter of lights is waiting.",
  "I hope today treated your thoughts with gentleness. Welcome back.",
  "Welcome back to the Wishverse, Deepal.",
  "A beautiful, warm thought has been saved for your return.",
  "Welcome back. Sit back, relax, and let the stars twinkle.",
  "It is always a special moment when you return, Deepal.",
  "Welcome back. The celestial wind is blowing softly.",
  "I hope today brought you steady progress and joy. Welcome back.",
  "Welcome back, Deepal. May this visit lift your spirit.",
  "The stardust waves are ready to echo. Welcome back.",
  "Welcome back. Let the soft light guide you.",
  "I'm glad you've returned to your quiet anchor.",
  "Welcome back, Deepal. I hope you feel valued and respected.",
  "The stars are singing a silent melody for your return.",
  "Welcome back. Breathe out the noise, breathe in the stardust.",
  "Welcome back, Deepal. Your space is as steady as ever.",
  "I hope today allowed you to stay true to your beautiful self.",
  "Welcome back. Let's find some cozy warmth together.",
  "Welcome back, Deepal. Your daily locket of care is ready.",
  "The universe is always a bit warmer when you are here.",
  "Welcome back. May this quiet sanctuary soothe your spirit.",
  "I'm glad your journey led you back to this harbor today.",
  "Welcome back, Deepal. I hope you enjoy today's custom surprise.",
  "The glowing stardust jar welcomes your gentle touch.",
  "Welcome back. May today bring a smooth end to your day.",
  "I hope you felt appreciated and understood today. Welcome back.",
  "Welcome back, Deepal. May your dreams be beautifully guided.",
  "Your private escape from the chaos is ready. Welcome back.",
  "Welcome back. Let the golden particles warm your eyes.",
  "I hope today was filled with gentle, helpful encounters.",
  "Welcome back, Deepal. Let the quiet rhythm ground you.",
  "The constellations are holding a special light for you.",
  "Welcome back. May you find quiet strength in this stillness.",
  "I'm glad you are back to check your daily surprise.",
  "Welcome back, Deepal. This place was made with you in mind.",
  "The wishing stardust is sparkling for your return.",
  "Welcome back. I hope your heart is light and untroubled.",
  "I hope you've had a lovely and fulfilling day. Welcome back.",
  "Welcome back, Deepal. May your evening be cozy and quiet.",
  "The digital universe is glad to have your warmth back.",
  "Welcome back. Enjoy your quiet time among the stars.",
  "I hope today allowed you to breathe fully. Welcome back.",
  "Welcome back, Deepal. You are always welcome in this sanctuary.",
  "The stars have aligned once more. Welcome back."
];

// Interactive Surprises configuration (365 unique indexes)
export interface DailySurpriseItem {
  id: number;
  type: "wish" | "quote" | "illustration" | "flower" | "butterfly" | "shooting_star" | "note" | "color_bg" | "constellation" | "floating_anim";
  title: string;
  subtitle: string;
  content: string;
  extraMeta?: string;
}

export const getSurpriseForIndex = (index: number): DailySurpriseItem => {
  // We can procedurally generate or lookup 365 unique items to guarantee 365 days of content
  const types: DailySurpriseItem["type"][] = [
    "note", "flower", "quote", "butterfly", "shooting_star", 
    "illustration", "color_bg", "constellation", "floating_anim", "wish"
  ];
  const type = types[index % types.length];

  const titles = [
    "Luminous Whisper", "Golden Blossom", "Celestial Beacon", "Emerald Flutter", "Midnight Meteor",
    "Stardust Canvas", "Aura Glow", "Cosmic Compass", "Nebula Drift", "Heartfelt Beacon"
  ];
  const title = `${titles[index % titles.length]} #${index + 1}`;

  const subtitles = [
    "A private handwritten note of respect", "An interactive blooming flower animation",
    "A handpicked editorial reflection", "An interactive guiding butterfly animation",
    "A custom shooting star launcher", "A hand-coded glowing vector illustration",
    "A warm new background color variation", "A rare constellation chart",
    "A soothing deep-space floating drift", "A stardust-infused heartfelt wish"
  ];
  const subtitle = subtitles[index % subtitles.length];

  let content = "";
  let extraMeta = "";

  if (type === "note") {
    const notes = [
      "Deepal, your kindness has a quiet way of making people feel valued. Never forget the beauty you bring to simple conversations.",
      "Just a tiny reminder that you do not have to carry everything alone. Let the stars take some of the weight today.",
      "In a fast-moving world, your authenticity is a refreshing gift. Thank you for always being genuine.",
      "Your strength is not loud, but it is deeply inspiring. May you have a gentle, untroubled day.",
      "You bring a quiet dignity to everything you do. Take proud steps today, knowing your efforts matter."
    ];
    content = notes[index % notes.length];
    extraMeta = "written with utmost care and respect";
  } else if (type === "quote") {
    const quotes = [
      "\"Grace is not standing out, but remaining unforgettable in the gentlest way.\"",
      "\"Silence is only empty if you do not know who is sharing it with you.\"",
      "\"May the stars always map themselves to match your quiet courage.\"",
      "\"Some people make the world brighter just by being in it. You are one of them.\"",
      "\"Never dim your light to make others comfortable. Your shine is your power.\""
    ];
    content = quotes[index % quotes.length];
    extraMeta = "a handpicked piece of wisdom";
  } else if (type === "wish") {
    content = DAILY_WISHES[index % DAILY_WISHES.length];
    extraMeta = "carrying warm thoughts from afar";
  } else if (type === "flower") {
    content = "Interact with the glowing lotus. Hover or tap to watch the golden petals expand and release glittering spores of stardust.";
    extraMeta = "interactive vector bloom";
  } else if (type === "butterfly") {
    content = "Move your cursor across the card. A glowing emerald butterfly will follow your touch, creating trails of stardust ripples.";
    extraMeta = "interactive cursor canvas companion";
  } else if (type === "shooting_star") {
    content = "Click the launch button below to release custom, high-fidelity shooting stars across your digital sky.";
    extraMeta = "celestial particle generator";
  } else if (type === "illustration") {
    content = "A beautiful abstract render of deep cosmic spheres aligned with the stars of July. Made as an elegant symbol of growth.";
    extraMeta = "coded high-contrast vector art";
  } else if (type === "color_bg") {
    content = "Today's background is infused with a soft lavender-rose aurora tint. Designed to create a warm, eye-safe space.";
    extraMeta = "custom ambient light adjustment";
  } else if (type === "constellation") {
    content = "The constellation of Lyra is especially bright tonight. It represents music, harmony, and the elegant alignment of moments.";
    extraMeta = "astronomical chart lock";
  } else {
    content = "A rhythmic, slow orbital floating animation. Designed to synchronize with relaxed breathing cycles.";
    extraMeta = "therapeutic screen movement";
  }

  return { id: index + 1, type, title, subtitle, content, extraMeta };
};
